# permissions for end users to view trinoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trino-viewer-role
rules:
- apiGroups:
  - tarim.deepexi.com
  resources:
  - trinoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tarim.deepexi.com
  resources:
  - trinoes/status
  verbs:
  - get
