apiVersion: tarim.deepexi.com/v1
kind: Trino
metadata:
  name: trino-sample
spec:
  cataLogConfig:
    tpcdsProperties: |
      connector.name=tpcds
      tpcds.splits-per-node=4
    tpchProperties: |
      connector.name=tpch
      tpch.splits-per-node=4
  coordinatorConfig:
    configProperties: |
      coordinator=true
      node-scheduler.include-coordinator=false
      http-server.http.port=8080
      query.max-memory=1GB
      query.max-memory-per-node=512MB
      query.max-total-memory-per-node=1GB
      memory.heap-headroom-per-node=512MB
      discovery.uri=http://localhost:8080
    jvmConfig: |
      -server
      -Xmx2G
      -XX:+UseG1GC
      -XX:G1HeapRegionSize=32M
      -XX:+UseGCOverheadLimit
      -XX:+ExplicitGCInvokesConcurrent
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:+ExitOnOutOfMemoryError
      -Djdk.attach.allowAttachSelf=true
      -XX:-UseBiasedLocking
      -XX:ReservedCodeCacheSize=512M
      -XX:PerMethodRecompilationCutoff=10000
      -XX:PerBytecodeRecompilationCutoff=10000
      -Djdk.nio.maxCachedBufferSize=2000000
    logProperties: |
      io.trino=INFO
    nodeProperties: |
      node.environment=production
      node.data-dir=/data/trino
      plugin.dir=/usr/lib/trino/plugin
    num: 1
    cpuRequest: 1
    memoryRequest: 1000
  workerConfig:
    configProperties: |
      coordinator=false
      node-scheduler.include-coordinator=false
      http-server.http.port=8080
      query.max-memory=1GB
      query.max-memory-per-node=512MB
      query.max-total-memory-per-node=1GB
      memory.heap-headroom-per-node=512MB
      discovery.uri=http://trino-sample-trino:8080
    jvmConfig: |
      -server
      -Xmx2G
      -XX:+UseG1GC
      -XX:G1HeapRegionSize=32M
      -XX:+UseGCOverheadLimit
      -XX:+ExplicitGCInvokesConcurrent
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:+ExitOnOutOfMemoryError
      -Djdk.attach.allowAttachSelf=true
      -XX:-UseBiasedLocking
      -XX:ReservedCodeCacheSize=512M
      -XX:PerMethodRecompilationCutoff=10000
      -XX:PerBytecodeRecompilationCutoff=10000
      -Djdk.nio.maxCachedBufferSize=2000000
    logProperties: |
      io.trino=INFO
    nodeProperties: |
      node.environment=production
      node.data-dir=/data/trino
      plugin.dir=/usr/lib/trino/plugin
    num: 2
    cpuRequest: 1
    memoryRequest: 1000
  pause: false
  nodePort: true

